/* automatically generated by rust-bindgen 0.72.1 */

pub const FT_DEVICE_DESCRIPTOR_TYPE: u32 = 1;
pub const FT_CONFIGURATION_DESCRIPTOR_TYPE: u32 = 2;
pub const FT_STRING_DESCRIPTOR_TYPE: u32 = 3;
pub const FT_INTERFACE_DESCRIPTOR_TYPE: u32 = 4;
pub const FT_RESERVED_INTERFACE_INDEX: u32 = 0;
pub const FT_RESERVED_PIPE_INDEX_SESSION: u32 = 0;
pub const FT_RESERVED_PIPE_INDEX_NOTIFICATION: u32 = 1;
pub const FT_RESERVED_PIPE_SESSION: u32 = 1;
pub const FT_RESERVED_PIPE_NOTIFICATION: u32 = 129;
pub const FT_OPEN_BY_SERIAL_NUMBER: u32 = 1;
pub const FT_OPEN_BY_DESCRIPTION: u32 = 2;
pub const FT_OPEN_BY_LOCATION: u32 = 4;
pub const FT_OPEN_BY_GUID: u32 = 8;
pub const FT_OPEN_BY_INDEX: u32 = 16;
pub const FT_LIST_ALL: u32 = 536870912;
pub const FT_LIST_BY_INDEX: u32 = 1073741824;
pub const FT_LIST_NUMBER_ONLY: u32 = 2147483648;
pub const FT_GPIO_DIRECTION_IN: u32 = 0;
pub const FT_GPIO_DIRECTION_OUT: u32 = 1;
pub const FT_GPIO_VALUE_LOW: u32 = 0;
pub const FT_GPIO_VALUE_HIGH: u32 = 1;
pub const FT_GPIO_0: u32 = 0;
pub const FT_GPIO_1: u32 = 1;
pub type DWORD = ::std::os::raw::c_uint;
pub type ULONG = ::std::os::raw::c_uint;
pub type USHORT = ::std::os::raw::c_ushort;
pub type UCHAR = ::std::os::raw::c_uchar;
pub type WORD = ::std::os::raw::c_ushort;
pub type WCHAR = ::std::os::raw::c_ushort;
pub type BYTE = ::std::os::raw::c_uchar;
pub type BOOL = ::std::os::raw::c_uint;
pub type PUCHAR = *mut UCHAR;
pub type LPCSTR = *const ::std::os::raw::c_char;
pub type PVOID = *mut ::std::os::raw::c_void;
pub type HANDLE = *mut ::std::os::raw::c_void;
pub type LPDWORD = *mut DWORD;
pub type PULONG = *mut ULONG;
pub type LPVOID = PVOID;
pub type VOID = ::std::os::raw::c_void;
pub type PUSHORT = *mut USHORT;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct _OVERLAPPED {
    pub Internal: DWORD,
    pub InternalHigh: DWORD,
    pub __bindgen_anon_1: _OVERLAPPED__bindgen_ty_1,
    pub hEvent: HANDLE,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union _OVERLAPPED__bindgen_ty_1 {
    pub __bindgen_anon_1: _OVERLAPPED__bindgen_ty_1__bindgen_ty_1,
    pub Pointer: PVOID,
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct _OVERLAPPED__bindgen_ty_1__bindgen_ty_1 {
    pub Offset: DWORD,
    pub OffsetHigh: DWORD,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of _OVERLAPPED__bindgen_ty_1__bindgen_ty_1"]
        [::std::mem::size_of::<_OVERLAPPED__bindgen_ty_1__bindgen_ty_1>() - 8usize];
    ["Alignment of _OVERLAPPED__bindgen_ty_1__bindgen_ty_1"]
        [::std::mem::align_of::<_OVERLAPPED__bindgen_ty_1__bindgen_ty_1>() - 4usize];
    ["Offset of field: _OVERLAPPED__bindgen_ty_1__bindgen_ty_1::Offset"]
        [::std::mem::offset_of!(_OVERLAPPED__bindgen_ty_1__bindgen_ty_1, Offset) - 0usize];
    ["Offset of field: _OVERLAPPED__bindgen_ty_1__bindgen_ty_1::OffsetHigh"]
        [::std::mem::offset_of!(_OVERLAPPED__bindgen_ty_1__bindgen_ty_1, OffsetHigh) - 4usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of _OVERLAPPED__bindgen_ty_1"]
        [::std::mem::size_of::<_OVERLAPPED__bindgen_ty_1>() - 8usize];
    ["Alignment of _OVERLAPPED__bindgen_ty_1"]
        [::std::mem::align_of::<_OVERLAPPED__bindgen_ty_1>() - 8usize];
    ["Offset of field: _OVERLAPPED__bindgen_ty_1::Pointer"]
        [::std::mem::offset_of!(_OVERLAPPED__bindgen_ty_1, Pointer) - 0usize];
};
impl Default for _OVERLAPPED__bindgen_ty_1 {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of _OVERLAPPED"][::std::mem::size_of::<_OVERLAPPED>() - 24usize];
    ["Alignment of _OVERLAPPED"][::std::mem::align_of::<_OVERLAPPED>() - 8usize];
    ["Offset of field: _OVERLAPPED::Internal"]
        [::std::mem::offset_of!(_OVERLAPPED, Internal) - 0usize];
    ["Offset of field: _OVERLAPPED::InternalHigh"]
        [::std::mem::offset_of!(_OVERLAPPED, InternalHigh) - 4usize];
    ["Offset of field: _OVERLAPPED::hEvent"][::std::mem::offset_of!(_OVERLAPPED, hEvent) - 16usize];
};
impl Default for _OVERLAPPED {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
pub type LPOVERLAPPED = *mut _OVERLAPPED;
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum _FT_FILTER_TYPE {
    FT_FILTER_NONE = 0,
    FT_FILTER_VID = 1,
    FT_FILTER_PID = 2,
    FT_FILTER_DESCRIPTION = 4,
}
pub use self::_FT_FILTER_TYPE as FT_FILTER_TYPE;
pub type FT_HANDLE = PVOID;
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum _FT_STATUS {
    FT_OK = 0,
    FT_INVALID_HANDLE = 1,
    FT_DEVICE_NOT_FOUND = 2,
    FT_DEVICE_NOT_OPENED = 3,
    FT_IO_ERROR = 4,
    FT_INSUFFICIENT_RESOURCES = 5,
    FT_INVALID_PARAMETER = 6,
    FT_INVALID_BAUD_RATE = 7,
    FT_DEVICE_NOT_OPENED_FOR_ERASE = 8,
    FT_DEVICE_NOT_OPENED_FOR_WRITE = 9,
    FT_FAILED_TO_WRITE_DEVICE = 10,
    FT_MEM_INSUFFICIENT_ERROR = 11,
    FT_OVERFLOW_ERROR = 12,
    FT_INVALID_ARGS = 16,
    FT_NOT_SUPPORTED = 17,
    FT_NO_MORE_ITEMS = 18,
    FT_TIMEOUT = 19,
    FT_OPERATION_ABORTED = 20,
    FT_RESERVED_PIPE = 21,
    FT_INVALID_CONTROL_REQUEST_DIRECTION = 22,
    FT_INVALID_CONTROL_REQUEST_TYPE = 23,
    FT_IO_PENDING = 24,
    FT_IO_INCOMPLETE = 25,
    FT_HANDLE_EOF = 26,
    FT_BUSY = 27,
    FT_NO_SYSTEM_RESOURCES = 28,
    FT_DEVICE_LIST_NOT_READY = 29,
    FT_DEVICE_NOT_CONNECTED = 30,
    FT_INCORRECT_DEVICE_PATH = 31,
    FT_OTHER_ERROR = 32,
}
pub type FT_STATUS = ULONG;
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum _FT_PIPE_TYPE {
    FTPipeTypeControl = 0,
    FTPipeTypeIsochronous = 1,
    FTPipeTypeBulk = 2,
    FTPipeTypeInterrupt = 3,
}
pub use self::_FT_PIPE_TYPE as FT_PIPE_TYPE;
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct _FT_COMMON_DESCRIPTOR {
    pub bLength: UCHAR,
    pub bDescriptorType: UCHAR,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of _FT_COMMON_DESCRIPTOR"][::std::mem::size_of::<_FT_COMMON_DESCRIPTOR>() - 2usize];
    ["Alignment of _FT_COMMON_DESCRIPTOR"]
        [::std::mem::align_of::<_FT_COMMON_DESCRIPTOR>() - 1usize];
    ["Offset of field: _FT_COMMON_DESCRIPTOR::bLength"]
        [::std::mem::offset_of!(_FT_COMMON_DESCRIPTOR, bLength) - 0usize];
    ["Offset of field: _FT_COMMON_DESCRIPTOR::bDescriptorType"]
        [::std::mem::offset_of!(_FT_COMMON_DESCRIPTOR, bDescriptorType) - 1usize];
};
pub type FT_COMMON_DESCRIPTOR = _FT_COMMON_DESCRIPTOR;
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct _FT_DEVICE_DESCRIPTOR {
    pub bLength: UCHAR,
    pub bDescriptorType: UCHAR,
    pub bcdUSB: USHORT,
    pub bDeviceClass: UCHAR,
    pub bDeviceSubClass: UCHAR,
    pub bDeviceProtocol: UCHAR,
    pub bMaxPacketSize0: UCHAR,
    pub idVendor: USHORT,
    pub idProduct: USHORT,
    pub bcdDevice: USHORT,
    pub iManufacturer: UCHAR,
    pub iProduct: UCHAR,
    pub iSerialNumber: UCHAR,
    pub bNumConfigurations: UCHAR,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of _FT_DEVICE_DESCRIPTOR"][::std::mem::size_of::<_FT_DEVICE_DESCRIPTOR>() - 18usize];
    ["Alignment of _FT_DEVICE_DESCRIPTOR"]
        [::std::mem::align_of::<_FT_DEVICE_DESCRIPTOR>() - 2usize];
    ["Offset of field: _FT_DEVICE_DESCRIPTOR::bLength"]
        [::std::mem::offset_of!(_FT_DEVICE_DESCRIPTOR, bLength) - 0usize];
    ["Offset of field: _FT_DEVICE_DESCRIPTOR::bDescriptorType"]
        [::std::mem::offset_of!(_FT_DEVICE_DESCRIPTOR, bDescriptorType) - 1usize];
    ["Offset of field: _FT_DEVICE_DESCRIPTOR::bcdUSB"]
        [::std::mem::offset_of!(_FT_DEVICE_DESCRIPTOR, bcdUSB) - 2usize];
    ["Offset of field: _FT_DEVICE_DESCRIPTOR::bDeviceClass"]
        [::std::mem::offset_of!(_FT_DEVICE_DESCRIPTOR, bDeviceClass) - 4usize];
    ["Offset of field: _FT_DEVICE_DESCRIPTOR::bDeviceSubClass"]
        [::std::mem::offset_of!(_FT_DEVICE_DESCRIPTOR, bDeviceSubClass) - 5usize];
    ["Offset of field: _FT_DEVICE_DESCRIPTOR::bDeviceProtocol"]
        [::std::mem::offset_of!(_FT_DEVICE_DESCRIPTOR, bDeviceProtocol) - 6usize];
    ["Offset of field: _FT_DEVICE_DESCRIPTOR::bMaxPacketSize0"]
        [::std::mem::offset_of!(_FT_DEVICE_DESCRIPTOR, bMaxPacketSize0) - 7usize];
    ["Offset of field: _FT_DEVICE_DESCRIPTOR::idVendor"]
        [::std::mem::offset_of!(_FT_DEVICE_DESCRIPTOR, idVendor) - 8usize];
    ["Offset of field: _FT_DEVICE_DESCRIPTOR::idProduct"]
        [::std::mem::offset_of!(_FT_DEVICE_DESCRIPTOR, idProduct) - 10usize];
    ["Offset of field: _FT_DEVICE_DESCRIPTOR::bcdDevice"]
        [::std::mem::offset_of!(_FT_DEVICE_DESCRIPTOR, bcdDevice) - 12usize];
    ["Offset of field: _FT_DEVICE_DESCRIPTOR::iManufacturer"]
        [::std::mem::offset_of!(_FT_DEVICE_DESCRIPTOR, iManufacturer) - 14usize];
    ["Offset of field: _FT_DEVICE_DESCRIPTOR::iProduct"]
        [::std::mem::offset_of!(_FT_DEVICE_DESCRIPTOR, iProduct) - 15usize];
    ["Offset of field: _FT_DEVICE_DESCRIPTOR::iSerialNumber"]
        [::std::mem::offset_of!(_FT_DEVICE_DESCRIPTOR, iSerialNumber) - 16usize];
    ["Offset of field: _FT_DEVICE_DESCRIPTOR::bNumConfigurations"]
        [::std::mem::offset_of!(_FT_DEVICE_DESCRIPTOR, bNumConfigurations) - 17usize];
};
pub type FT_DEVICE_DESCRIPTOR = _FT_DEVICE_DESCRIPTOR;
pub type PFT_DEVICE_DESCRIPTOR = *mut _FT_DEVICE_DESCRIPTOR;
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct _FT_CONFIGURATION_DESCRIPTOR {
    pub bLength: UCHAR,
    pub bDescriptorType: UCHAR,
    pub wTotalLength: USHORT,
    pub bNumInterfaces: UCHAR,
    pub bConfigurationValue: UCHAR,
    pub iConfiguration: UCHAR,
    pub bmAttributes: UCHAR,
    pub MaxPower: UCHAR,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of _FT_CONFIGURATION_DESCRIPTOR"]
        [::std::mem::size_of::<_FT_CONFIGURATION_DESCRIPTOR>() - 10usize];
    ["Alignment of _FT_CONFIGURATION_DESCRIPTOR"]
        [::std::mem::align_of::<_FT_CONFIGURATION_DESCRIPTOR>() - 2usize];
    ["Offset of field: _FT_CONFIGURATION_DESCRIPTOR::bLength"]
        [::std::mem::offset_of!(_FT_CONFIGURATION_DESCRIPTOR, bLength) - 0usize];
    ["Offset of field: _FT_CONFIGURATION_DESCRIPTOR::bDescriptorType"]
        [::std::mem::offset_of!(_FT_CONFIGURATION_DESCRIPTOR, bDescriptorType) - 1usize];
    ["Offset of field: _FT_CONFIGURATION_DESCRIPTOR::wTotalLength"]
        [::std::mem::offset_of!(_FT_CONFIGURATION_DESCRIPTOR, wTotalLength) - 2usize];
    ["Offset of field: _FT_CONFIGURATION_DESCRIPTOR::bNumInterfaces"]
        [::std::mem::offset_of!(_FT_CONFIGURATION_DESCRIPTOR, bNumInterfaces) - 4usize];
    ["Offset of field: _FT_CONFIGURATION_DESCRIPTOR::bConfigurationValue"]
        [::std::mem::offset_of!(_FT_CONFIGURATION_DESCRIPTOR, bConfigurationValue) - 5usize];
    ["Offset of field: _FT_CONFIGURATION_DESCRIPTOR::iConfiguration"]
        [::std::mem::offset_of!(_FT_CONFIGURATION_DESCRIPTOR, iConfiguration) - 6usize];
    ["Offset of field: _FT_CONFIGURATION_DESCRIPTOR::bmAttributes"]
        [::std::mem::offset_of!(_FT_CONFIGURATION_DESCRIPTOR, bmAttributes) - 7usize];
    ["Offset of field: _FT_CONFIGURATION_DESCRIPTOR::MaxPower"]
        [::std::mem::offset_of!(_FT_CONFIGURATION_DESCRIPTOR, MaxPower) - 8usize];
};
pub type FT_CONFIGURATION_DESCRIPTOR = _FT_CONFIGURATION_DESCRIPTOR;
pub type PFT_CONFIGURATION_DESCRIPTOR = *mut _FT_CONFIGURATION_DESCRIPTOR;
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct _FT_INTERFACE_DESCRIPTOR {
    pub bLength: UCHAR,
    pub bDescriptorType: UCHAR,
    pub bInterfaceNumber: UCHAR,
    pub bAlternateSetting: UCHAR,
    pub bNumEndpoints: UCHAR,
    pub bInterfaceClass: UCHAR,
    pub bInterfaceSubClass: UCHAR,
    pub bInterfaceProtocol: UCHAR,
    pub iInterface: UCHAR,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of _FT_INTERFACE_DESCRIPTOR"]
        [::std::mem::size_of::<_FT_INTERFACE_DESCRIPTOR>() - 9usize];
    ["Alignment of _FT_INTERFACE_DESCRIPTOR"]
        [::std::mem::align_of::<_FT_INTERFACE_DESCRIPTOR>() - 1usize];
    ["Offset of field: _FT_INTERFACE_DESCRIPTOR::bLength"]
        [::std::mem::offset_of!(_FT_INTERFACE_DESCRIPTOR, bLength) - 0usize];
    ["Offset of field: _FT_INTERFACE_DESCRIPTOR::bDescriptorType"]
        [::std::mem::offset_of!(_FT_INTERFACE_DESCRIPTOR, bDescriptorType) - 1usize];
    ["Offset of field: _FT_INTERFACE_DESCRIPTOR::bInterfaceNumber"]
        [::std::mem::offset_of!(_FT_INTERFACE_DESCRIPTOR, bInterfaceNumber) - 2usize];
    ["Offset of field: _FT_INTERFACE_DESCRIPTOR::bAlternateSetting"]
        [::std::mem::offset_of!(_FT_INTERFACE_DESCRIPTOR, bAlternateSetting) - 3usize];
    ["Offset of field: _FT_INTERFACE_DESCRIPTOR::bNumEndpoints"]
        [::std::mem::offset_of!(_FT_INTERFACE_DESCRIPTOR, bNumEndpoints) - 4usize];
    ["Offset of field: _FT_INTERFACE_DESCRIPTOR::bInterfaceClass"]
        [::std::mem::offset_of!(_FT_INTERFACE_DESCRIPTOR, bInterfaceClass) - 5usize];
    ["Offset of field: _FT_INTERFACE_DESCRIPTOR::bInterfaceSubClass"]
        [::std::mem::offset_of!(_FT_INTERFACE_DESCRIPTOR, bInterfaceSubClass) - 6usize];
    ["Offset of field: _FT_INTERFACE_DESCRIPTOR::bInterfaceProtocol"]
        [::std::mem::offset_of!(_FT_INTERFACE_DESCRIPTOR, bInterfaceProtocol) - 7usize];
    ["Offset of field: _FT_INTERFACE_DESCRIPTOR::iInterface"]
        [::std::mem::offset_of!(_FT_INTERFACE_DESCRIPTOR, iInterface) - 8usize];
};
pub type FT_INTERFACE_DESCRIPTOR = _FT_INTERFACE_DESCRIPTOR;
pub type PFT_INTERFACE_DESCRIPTOR = *mut _FT_INTERFACE_DESCRIPTOR;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _FT_STRING_DESCRIPTOR {
    pub bLength: UCHAR,
    pub bDescriptorType: UCHAR,
    pub szString: [WCHAR; 256usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of _FT_STRING_DESCRIPTOR"][::std::mem::size_of::<_FT_STRING_DESCRIPTOR>() - 514usize];
    ["Alignment of _FT_STRING_DESCRIPTOR"]
        [::std::mem::align_of::<_FT_STRING_DESCRIPTOR>() - 2usize];
    ["Offset of field: _FT_STRING_DESCRIPTOR::bLength"]
        [::std::mem::offset_of!(_FT_STRING_DESCRIPTOR, bLength) - 0usize];
    ["Offset of field: _FT_STRING_DESCRIPTOR::bDescriptorType"]
        [::std::mem::offset_of!(_FT_STRING_DESCRIPTOR, bDescriptorType) - 1usize];
    ["Offset of field: _FT_STRING_DESCRIPTOR::szString"]
        [::std::mem::offset_of!(_FT_STRING_DESCRIPTOR, szString) - 2usize];
};
impl Default for _FT_STRING_DESCRIPTOR {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
pub type FT_STRING_DESCRIPTOR = _FT_STRING_DESCRIPTOR;
pub type PFT_STRING_DESCRIPTOR = *mut _FT_STRING_DESCRIPTOR;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _FT_PIPE_INFORMATION {
    pub PipeType: FT_PIPE_TYPE,
    pub PipeId: UCHAR,
    pub MaximumPacketSize: USHORT,
    pub Interval: UCHAR,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of _FT_PIPE_INFORMATION"][::std::mem::size_of::<_FT_PIPE_INFORMATION>() - 12usize];
    ["Alignment of _FT_PIPE_INFORMATION"][::std::mem::align_of::<_FT_PIPE_INFORMATION>() - 4usize];
    ["Offset of field: _FT_PIPE_INFORMATION::PipeType"]
        [::std::mem::offset_of!(_FT_PIPE_INFORMATION, PipeType) - 0usize];
    ["Offset of field: _FT_PIPE_INFORMATION::PipeId"]
        [::std::mem::offset_of!(_FT_PIPE_INFORMATION, PipeId) - 4usize];
    ["Offset of field: _FT_PIPE_INFORMATION::MaximumPacketSize"]
        [::std::mem::offset_of!(_FT_PIPE_INFORMATION, MaximumPacketSize) - 6usize];
    ["Offset of field: _FT_PIPE_INFORMATION::Interval"]
        [::std::mem::offset_of!(_FT_PIPE_INFORMATION, Interval) - 8usize];
};
impl Default for _FT_PIPE_INFORMATION {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
pub type FT_PIPE_INFORMATION = _FT_PIPE_INFORMATION;
pub type PFT_PIPE_INFORMATION = *mut _FT_PIPE_INFORMATION;
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct _FT_SETUP_PACKET {
    pub RequestType: UCHAR,
    pub Request: UCHAR,
    pub Value: USHORT,
    pub Index: USHORT,
    pub Length: USHORT,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of _FT_SETUP_PACKET"][::std::mem::size_of::<_FT_SETUP_PACKET>() - 8usize];
    ["Alignment of _FT_SETUP_PACKET"][::std::mem::align_of::<_FT_SETUP_PACKET>() - 2usize];
    ["Offset of field: _FT_SETUP_PACKET::RequestType"]
        [::std::mem::offset_of!(_FT_SETUP_PACKET, RequestType) - 0usize];
    ["Offset of field: _FT_SETUP_PACKET::Request"]
        [::std::mem::offset_of!(_FT_SETUP_PACKET, Request) - 1usize];
    ["Offset of field: _FT_SETUP_PACKET::Value"]
        [::std::mem::offset_of!(_FT_SETUP_PACKET, Value) - 2usize];
    ["Offset of field: _FT_SETUP_PACKET::Index"]
        [::std::mem::offset_of!(_FT_SETUP_PACKET, Index) - 4usize];
    ["Offset of field: _FT_SETUP_PACKET::Length"]
        [::std::mem::offset_of!(_FT_SETUP_PACKET, Length) - 6usize];
};
pub type FT_SETUP_PACKET = _FT_SETUP_PACKET;
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum _E_FT_NOTIFICATION_CALLBACK_TYPE {
    E_FT_NOTIFICATION_CALLBACK_TYPE_DATA = 0,
    E_FT_NOTIFICATION_CALLBACK_TYPE_GPIO = 1,
    E_FT_NOTIFICATION_CALLBACK_TYPE_INTERRUPT = 2,
}
pub use self::_E_FT_NOTIFICATION_CALLBACK_TYPE as E_FT_NOTIFICATION_CALLBACK_TYPE;
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct _FT_NOTIFICATION_CALLBACK_INFO_DATA {
    pub ulRecvNotificationLength: ULONG,
    pub ucEndpointNo: UCHAR,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of _FT_NOTIFICATION_CALLBACK_INFO_DATA"]
        [::std::mem::size_of::<_FT_NOTIFICATION_CALLBACK_INFO_DATA>() - 8usize];
    ["Alignment of _FT_NOTIFICATION_CALLBACK_INFO_DATA"]
        [::std::mem::align_of::<_FT_NOTIFICATION_CALLBACK_INFO_DATA>() - 4usize];
    ["Offset of field: _FT_NOTIFICATION_CALLBACK_INFO_DATA::ulRecvNotificationLength"][::std::mem::offset_of!(
        _FT_NOTIFICATION_CALLBACK_INFO_DATA,
        ulRecvNotificationLength
    ) - 0usize];
    ["Offset of field: _FT_NOTIFICATION_CALLBACK_INFO_DATA::ucEndpointNo"]
        [::std::mem::offset_of!(_FT_NOTIFICATION_CALLBACK_INFO_DATA, ucEndpointNo) - 4usize];
};
pub type FT_NOTIFICATION_CALLBACK_INFO_DATA = _FT_NOTIFICATION_CALLBACK_INFO_DATA;
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct _FT_NOTIFICATION_CALLBACK_INFO_GPIO {
    pub bGPIO0: BOOL,
    pub bGPIO1: BOOL,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of _FT_NOTIFICATION_CALLBACK_INFO_GPIO"]
        [::std::mem::size_of::<_FT_NOTIFICATION_CALLBACK_INFO_GPIO>() - 8usize];
    ["Alignment of _FT_NOTIFICATION_CALLBACK_INFO_GPIO"]
        [::std::mem::align_of::<_FT_NOTIFICATION_CALLBACK_INFO_GPIO>() - 4usize];
    ["Offset of field: _FT_NOTIFICATION_CALLBACK_INFO_GPIO::bGPIO0"]
        [::std::mem::offset_of!(_FT_NOTIFICATION_CALLBACK_INFO_GPIO, bGPIO0) - 0usize];
    ["Offset of field: _FT_NOTIFICATION_CALLBACK_INFO_GPIO::bGPIO1"]
        [::std::mem::offset_of!(_FT_NOTIFICATION_CALLBACK_INFO_GPIO, bGPIO1) - 4usize];
};
pub type FT_NOTIFICATION_CALLBACK_INFO_GPIO = _FT_NOTIFICATION_CALLBACK_INFO_GPIO;
pub type FT_NOTIFICATION_CALLBACK = ::std::option::Option<
    unsafe extern "C" fn(
        pvCallbackContext: PVOID,
        eCallbackType: E_FT_NOTIFICATION_CALLBACK_TYPE,
        pvCallbackInfo: PVOID,
    ),
>;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FT_60XCONFIGURATION {
    pub VendorID: USHORT,
    pub ProductID: USHORT,
    pub StringDescriptors: [UCHAR; 128usize],
    pub bInterval: UCHAR,
    pub PowerAttributes: UCHAR,
    pub PowerConsumption: USHORT,
    pub Reserved2: UCHAR,
    pub FIFOClock: UCHAR,
    pub FIFOMode: UCHAR,
    pub ChannelConfig: UCHAR,
    pub OptionalFeatureSupport: USHORT,
    pub BatteryChargingGPIOConfig: UCHAR,
    pub FlashEEPROMDetection: UCHAR,
    pub MSIO_Control: ULONG,
    pub GPIO_Control: ULONG,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of FT_60XCONFIGURATION"][::std::mem::size_of::<FT_60XCONFIGURATION>() - 152usize];
    ["Alignment of FT_60XCONFIGURATION"][::std::mem::align_of::<FT_60XCONFIGURATION>() - 4usize];
    ["Offset of field: FT_60XCONFIGURATION::VendorID"]
        [::std::mem::offset_of!(FT_60XCONFIGURATION, VendorID) - 0usize];
    ["Offset of field: FT_60XCONFIGURATION::ProductID"]
        [::std::mem::offset_of!(FT_60XCONFIGURATION, ProductID) - 2usize];
    ["Offset of field: FT_60XCONFIGURATION::StringDescriptors"]
        [::std::mem::offset_of!(FT_60XCONFIGURATION, StringDescriptors) - 4usize];
    ["Offset of field: FT_60XCONFIGURATION::bInterval"]
        [::std::mem::offset_of!(FT_60XCONFIGURATION, bInterval) - 132usize];
    ["Offset of field: FT_60XCONFIGURATION::PowerAttributes"]
        [::std::mem::offset_of!(FT_60XCONFIGURATION, PowerAttributes) - 133usize];
    ["Offset of field: FT_60XCONFIGURATION::PowerConsumption"]
        [::std::mem::offset_of!(FT_60XCONFIGURATION, PowerConsumption) - 134usize];
    ["Offset of field: FT_60XCONFIGURATION::Reserved2"]
        [::std::mem::offset_of!(FT_60XCONFIGURATION, Reserved2) - 136usize];
    ["Offset of field: FT_60XCONFIGURATION::FIFOClock"]
        [::std::mem::offset_of!(FT_60XCONFIGURATION, FIFOClock) - 137usize];
    ["Offset of field: FT_60XCONFIGURATION::FIFOMode"]
        [::std::mem::offset_of!(FT_60XCONFIGURATION, FIFOMode) - 138usize];
    ["Offset of field: FT_60XCONFIGURATION::ChannelConfig"]
        [::std::mem::offset_of!(FT_60XCONFIGURATION, ChannelConfig) - 139usize];
    ["Offset of field: FT_60XCONFIGURATION::OptionalFeatureSupport"]
        [::std::mem::offset_of!(FT_60XCONFIGURATION, OptionalFeatureSupport) - 140usize];
    ["Offset of field: FT_60XCONFIGURATION::BatteryChargingGPIOConfig"]
        [::std::mem::offset_of!(FT_60XCONFIGURATION, BatteryChargingGPIOConfig) - 142usize];
    ["Offset of field: FT_60XCONFIGURATION::FlashEEPROMDetection"]
        [::std::mem::offset_of!(FT_60XCONFIGURATION, FlashEEPROMDetection) - 143usize];
    ["Offset of field: FT_60XCONFIGURATION::MSIO_Control"]
        [::std::mem::offset_of!(FT_60XCONFIGURATION, MSIO_Control) - 144usize];
    ["Offset of field: FT_60XCONFIGURATION::GPIO_Control"]
        [::std::mem::offset_of!(FT_60XCONFIGURATION, GPIO_Control) - 148usize];
};
impl Default for FT_60XCONFIGURATION {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum _FT_DEVICE {
    FT_DEVICE_UNKNOWN = 3,
    FT_DEVICE_600 = 600,
    FT_DEVICE_601 = 601,
    FT_DEVICE_602 = 602,
    FT_DEVICE_603 = 603,
}
pub use self::_FT_DEVICE as FT_DEVICE;
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum _FT_FLAGS {
    FT_FLAGS_OPENED = 1,
    FT_FLAGS_HISPEED = 2,
    FT_FLAGS_SUPERSPEED = 4,
}
pub use self::_FT_FLAGS as FT_FLAGS;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _FT_DEVICE_LIST_INFO_NODE {
    pub Flags: ULONG,
    pub Type: ULONG,
    pub ID: ULONG,
    pub LocId: DWORD,
    pub SerialNumber: [::std::os::raw::c_char; 16usize],
    pub Description: [::std::os::raw::c_char; 32usize],
    pub ftHandle: FT_HANDLE,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of _FT_DEVICE_LIST_INFO_NODE"]
        [::std::mem::size_of::<_FT_DEVICE_LIST_INFO_NODE>() - 72usize];
    ["Alignment of _FT_DEVICE_LIST_INFO_NODE"]
        [::std::mem::align_of::<_FT_DEVICE_LIST_INFO_NODE>() - 8usize];
    ["Offset of field: _FT_DEVICE_LIST_INFO_NODE::Flags"]
        [::std::mem::offset_of!(_FT_DEVICE_LIST_INFO_NODE, Flags) - 0usize];
    ["Offset of field: _FT_DEVICE_LIST_INFO_NODE::Type"]
        [::std::mem::offset_of!(_FT_DEVICE_LIST_INFO_NODE, Type) - 4usize];
    ["Offset of field: _FT_DEVICE_LIST_INFO_NODE::ID"]
        [::std::mem::offset_of!(_FT_DEVICE_LIST_INFO_NODE, ID) - 8usize];
    ["Offset of field: _FT_DEVICE_LIST_INFO_NODE::LocId"]
        [::std::mem::offset_of!(_FT_DEVICE_LIST_INFO_NODE, LocId) - 12usize];
    ["Offset of field: _FT_DEVICE_LIST_INFO_NODE::SerialNumber"]
        [::std::mem::offset_of!(_FT_DEVICE_LIST_INFO_NODE, SerialNumber) - 16usize];
    ["Offset of field: _FT_DEVICE_LIST_INFO_NODE::Description"]
        [::std::mem::offset_of!(_FT_DEVICE_LIST_INFO_NODE, Description) - 32usize];
    ["Offset of field: _FT_DEVICE_LIST_INFO_NODE::ftHandle"]
        [::std::mem::offset_of!(_FT_DEVICE_LIST_INFO_NODE, ftHandle) - 64usize];
};
impl Default for _FT_DEVICE_LIST_INFO_NODE {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
pub type FT_DEVICE_LIST_INFO_NODE = _FT_DEVICE_LIST_INFO_NODE;
impl FT_GPIO_PULL {
    pub const GPIO_PULL_DEFAULT: FT_GPIO_PULL = FT_GPIO_PULL::GPIO_PULL_50K_PD;
}
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum FT_GPIO_PULL {
    GPIO_PULL_50K_PD = 0,
    GPIO_PULL_HIZ = 1,
    GPIO_PULL_50K_PU = 2,
}
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum FT_PIPE_DIRECTION {
    FT_PIPE_DIR_IN = 0,
    FT_PIPE_DIR_OUT = 1,
    FT_PIPE_DIR_COUNT = 2,
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct FT_PIPE_TRANSFER_CONF {
    pub fPipeNotUsed: BOOL,
    pub fNonThreadSafeTransfer: BOOL,
    pub bURBCount: BYTE,
    pub wURBBufferCount: WORD,
    pub dwURBBufferSize: DWORD,
    pub dwStreamingSize: DWORD,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of FT_PIPE_TRANSFER_CONF"][::std::mem::size_of::<FT_PIPE_TRANSFER_CONF>() - 20usize];
    ["Alignment of FT_PIPE_TRANSFER_CONF"]
        [::std::mem::align_of::<FT_PIPE_TRANSFER_CONF>() - 4usize];
    ["Offset of field: FT_PIPE_TRANSFER_CONF::fPipeNotUsed"]
        [::std::mem::offset_of!(FT_PIPE_TRANSFER_CONF, fPipeNotUsed) - 0usize];
    ["Offset of field: FT_PIPE_TRANSFER_CONF::fNonThreadSafeTransfer"]
        [::std::mem::offset_of!(FT_PIPE_TRANSFER_CONF, fNonThreadSafeTransfer) - 4usize];
    ["Offset of field: FT_PIPE_TRANSFER_CONF::bURBCount"]
        [::std::mem::offset_of!(FT_PIPE_TRANSFER_CONF, bURBCount) - 8usize];
    ["Offset of field: FT_PIPE_TRANSFER_CONF::wURBBufferCount"]
        [::std::mem::offset_of!(FT_PIPE_TRANSFER_CONF, wURBBufferCount) - 10usize];
    ["Offset of field: FT_PIPE_TRANSFER_CONF::dwURBBufferSize"]
        [::std::mem::offset_of!(FT_PIPE_TRANSFER_CONF, dwURBBufferSize) - 12usize];
    ["Offset of field: FT_PIPE_TRANSFER_CONF::dwStreamingSize"]
        [::std::mem::offset_of!(FT_PIPE_TRANSFER_CONF, dwStreamingSize) - 16usize];
};
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct _FT_TRANSFER_CONF {
    pub wStructSize: WORD,
    pub pipe: [FT_PIPE_TRANSFER_CONF; 2usize],
    pub fStopReadingOnURBUnderrun: BOOL,
    pub fBitBangMode: BOOL,
    pub fKeepDeviceSideBufferAfterReopen: BOOL,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of _FT_TRANSFER_CONF"][::std::mem::size_of::<_FT_TRANSFER_CONF>() - 56usize];
    ["Alignment of _FT_TRANSFER_CONF"][::std::mem::align_of::<_FT_TRANSFER_CONF>() - 4usize];
    ["Offset of field: _FT_TRANSFER_CONF::wStructSize"]
        [::std::mem::offset_of!(_FT_TRANSFER_CONF, wStructSize) - 0usize];
    ["Offset of field: _FT_TRANSFER_CONF::pipe"]
        [::std::mem::offset_of!(_FT_TRANSFER_CONF, pipe) - 4usize];
    ["Offset of field: _FT_TRANSFER_CONF::fStopReadingOnURBUnderrun"]
        [::std::mem::offset_of!(_FT_TRANSFER_CONF, fStopReadingOnURBUnderrun) - 44usize];
    ["Offset of field: _FT_TRANSFER_CONF::fBitBangMode"]
        [::std::mem::offset_of!(_FT_TRANSFER_CONF, fBitBangMode) - 48usize];
    ["Offset of field: _FT_TRANSFER_CONF::fKeepDeviceSideBufferAfterReopen"]
        [::std::mem::offset_of!(_FT_TRANSFER_CONF, fKeepDeviceSideBufferAfterReopen) - 52usize];
};
pub type FT_TRANSFER_CONF = _FT_TRANSFER_CONF;
unsafe extern "C" {
    pub fn FT_Create(pvArg: PVOID, dwFlags: DWORD, pftHandle: *mut FT_HANDLE) -> FT_STATUS;
}
unsafe extern "C" {
    pub fn FT_Close(ftHandle: FT_HANDLE) -> FT_STATUS;
}
unsafe extern "C" {
    pub fn FT_GetVIDPID(ftHandle: FT_HANDLE, puwVID: PUSHORT, puwPID: PUSHORT) -> FT_STATUS;
}
unsafe extern "C" {
    pub fn FT_WritePipe(
        ftHandle: FT_HANDLE,
        ucPipeID: UCHAR,
        pucBuffer: PUCHAR,
        ulBufferLength: ULONG,
        pulBytesTransferred: PULONG,
        dwTimeoutInMs: DWORD,
    ) -> FT_STATUS;
}
unsafe extern "C" {
    pub fn FT_ReadPipe(
        ftHandle: FT_HANDLE,
        ucPipeID: UCHAR,
        pucBuffer: PUCHAR,
        ulBufferLength: ULONG,
        pulBytesTransferred: PULONG,
        dwTimeoutInMs: DWORD,
    ) -> FT_STATUS;
}
unsafe extern "C" {
    pub fn FT_WritePipeEx(
        ftHandle: FT_HANDLE,
        ucFifoID: UCHAR,
        pucBuffer: PUCHAR,
        ulBufferLength: ULONG,
        pulBytesTransferred: PULONG,
        dwTimeoutInMs: DWORD,
    ) -> FT_STATUS;
}
unsafe extern "C" {
    pub fn FT_WritePipeAsync(
        ftHandle: FT_HANDLE,
        ucFifoID: UCHAR,
        pucBuffer: PUCHAR,
        ulBufferLength: ULONG,
        pulBytesTransferred: PULONG,
        pOverlapped: LPOVERLAPPED,
    ) -> FT_STATUS;
}
unsafe extern "C" {
    pub fn FT_ReadPipeEx(
        ftHandle: FT_HANDLE,
        ucFifoID: UCHAR,
        pucBuffer: PUCHAR,
        ulBufferLength: ULONG,
        pulBytesTransferred: PULONG,
        dwTimeoutInMs: DWORD,
    ) -> FT_STATUS;
}
unsafe extern "C" {
    pub fn FT_ReadPipeAsync(
        ftHandle: FT_HANDLE,
        ucFifoID: UCHAR,
        pucBuffer: PUCHAR,
        ulBufferLength: ULONG,
        pulBytesTransferred: PULONG,
        pOverlapped: LPOVERLAPPED,
    ) -> FT_STATUS;
}
unsafe extern "C" {
    pub fn FT_GetOverlappedResult(
        ftHandle: FT_HANDLE,
        pOverlapped: LPOVERLAPPED,
        pulBytesTransferred: PULONG,
        bWait: BOOL,
    ) -> FT_STATUS;
}
unsafe extern "C" {
    pub fn FT_InitializeOverlapped(ftHandle: FT_HANDLE, pOverlapped: LPOVERLAPPED) -> FT_STATUS;
}
unsafe extern "C" {
    pub fn FT_ReleaseOverlapped(ftHandle: FT_HANDLE, pOverlapped: LPOVERLAPPED) -> FT_STATUS;
}
unsafe extern "C" {
    pub fn FT_SetStreamPipe(
        ftHandle: FT_HANDLE,
        bAllWritePipes: BOOL,
        bAllReadPipes: BOOL,
        ucPipeID: UCHAR,
        ulStreamSize: ULONG,
    ) -> FT_STATUS;
}
unsafe extern "C" {
    pub fn FT_ClearStreamPipe(
        ftHandle: FT_HANDLE,
        bAllWritePipes: BOOL,
        bAllReadPipes: BOOL,
        ucPipeID: UCHAR,
    ) -> FT_STATUS;
}
unsafe extern "C" {
    pub fn FT_FlushPipe(ftHandle: FT_HANDLE, ucPipeID: UCHAR) -> FT_STATUS;
}
unsafe extern "C" {
    pub fn FT_AbortPipe(ftHandle: FT_HANDLE, ucPipeID: UCHAR) -> FT_STATUS;
}
unsafe extern "C" {
    pub fn FT_GetDeviceDescriptor(
        ftHandle: FT_HANDLE,
        ptDescriptor: PFT_DEVICE_DESCRIPTOR,
    ) -> FT_STATUS;
}
unsafe extern "C" {
    pub fn FT_GetConfigurationDescriptor(
        ftHandle: FT_HANDLE,
        ptDescriptor: PFT_CONFIGURATION_DESCRIPTOR,
    ) -> FT_STATUS;
}
unsafe extern "C" {
    pub fn FT_GetInterfaceDescriptor(
        ftHandle: FT_HANDLE,
        ucInterfaceIndex: UCHAR,
        ptDescriptor: PFT_INTERFACE_DESCRIPTOR,
    ) -> FT_STATUS;
}
unsafe extern "C" {
    pub fn FT_GetPipeInformation(
        ftHandle: FT_HANDLE,
        ucInterfaceIndex: UCHAR,
        ucPipeID: UCHAR,
        ptPipeInformation: PFT_PIPE_INFORMATION,
    ) -> FT_STATUS;
}
unsafe extern "C" {
    pub fn FT_GetStringDescriptor(
        ftHandle: FT_HANDLE,
        ucStringIndex: UCHAR,
        ptDescriptor: PFT_STRING_DESCRIPTOR,
    ) -> FT_STATUS;
}
unsafe extern "C" {
    pub fn FT_GetDescriptor(
        ftHandle: FT_HANDLE,
        ucDescriptorType: UCHAR,
        ucIndex: UCHAR,
        pucBuffer: PUCHAR,
        ulBufferLength: ULONG,
        pulLengthTransferred: PULONG,
    ) -> FT_STATUS;
}
unsafe extern "C" {
    pub fn FT_ControlTransfer(
        ftHandle: FT_HANDLE,
        tSetupPacket: FT_SETUP_PACKET,
        pucBuffer: PUCHAR,
        ulBufferLength: ULONG,
        pulLengthTransferred: PULONG,
    ) -> FT_STATUS;
}
unsafe extern "C" {
    pub fn FT_SetNotificationCallback(
        ftHandle: FT_HANDLE,
        pCallback: FT_NOTIFICATION_CALLBACK,
        pvCallbackContext: PVOID,
    ) -> FT_STATUS;
}
unsafe extern "C" {
    pub fn FT_ClearNotificationCallback(ftHandle: FT_HANDLE);
}
unsafe extern "C" {
    pub fn FT_GetChipConfiguration(ftHandle: FT_HANDLE, pvConfiguration: PVOID) -> FT_STATUS;
}
unsafe extern "C" {
    pub fn FT_SetChipConfiguration(ftHandle: FT_HANDLE, pvConfiguration: PVOID) -> FT_STATUS;
}
unsafe extern "C" {
    pub fn FT_GetFirmwareVersion(ftHandle: FT_HANDLE, pulFirmwareVersion: PULONG) -> FT_STATUS;
}
unsafe extern "C" {
    pub fn FT_ResetDevicePort(ftHandle: FT_HANDLE) -> FT_STATUS;
}
unsafe extern "C" {
    pub fn FT_CycleDevicePort(ftHandle: FT_HANDLE) -> FT_STATUS;
}
unsafe extern "C" {
    pub fn FT_CreateDeviceInfoList(lpdwNumDevs: LPDWORD) -> FT_STATUS;
}
unsafe extern "C" {
    pub fn FT_GetDeviceInfoList(
        ptDest: *mut FT_DEVICE_LIST_INFO_NODE,
        lpdwNumDevs: LPDWORD,
    ) -> FT_STATUS;
}
unsafe extern "C" {
    pub fn FT_GetDeviceInfoDetail(
        dwIndex: DWORD,
        lpdwFlags: LPDWORD,
        lpdwType: LPDWORD,
        lpdwID: LPDWORD,
        lpdwLocId: LPDWORD,
        lpSerialNumber: LPVOID,
        lpDescription: LPVOID,
        pftHandle: *mut FT_HANDLE,
    ) -> FT_STATUS;
}
unsafe extern "C" {
    pub fn FT_ListDevices(pArg1: PVOID, pArg2: PVOID, Flags: DWORD) -> FT_STATUS;
}
unsafe extern "C" {
    pub fn FT_IsDevicePath(ftHandle: FT_HANDLE, pucDevicePath: LPCSTR) -> FT_STATUS;
}
unsafe extern "C" {
    pub fn FT_GetDriverVersion(ftHandle: FT_HANDLE, lpdwVersion: LPDWORD) -> FT_STATUS;
}
unsafe extern "C" {
    pub fn FT_GetLibraryVersion(lpdwVersion: LPDWORD) -> FT_STATUS;
}
unsafe extern "C" {
    pub fn FT_SetPipeTimeout(
        ftHandle: FT_HANDLE,
        ucPipeID: UCHAR,
        dwTimeoutInMs: DWORD,
    ) -> FT_STATUS;
}
unsafe extern "C" {
    pub fn FT_EnableGPIO(ftHandle: FT_HANDLE, dwMask: DWORD, dwDirection: DWORD) -> FT_STATUS;
}
unsafe extern "C" {
    pub fn FT_WriteGPIO(ftHandle: FT_HANDLE, dwMask: DWORD, dwLevel: DWORD) -> FT_STATUS;
}
unsafe extern "C" {
    pub fn FT_ReadGPIO(ftHandle: FT_HANDLE, pdwData: *mut DWORD) -> FT_STATUS;
}
unsafe extern "C" {
    pub fn FT_SetGPIOPull(ftHandle: FT_HANDLE, dwMask: DWORD, dwPull: DWORD) -> FT_STATUS;
}
unsafe extern "C" {
    pub fn FT_SetGPIO(ftHandle: FT_HANDLE, ucDirection: UCHAR, ucValue: UCHAR) -> FT_STATUS;
}
unsafe extern "C" {
    pub fn FT_GetGPIO(
        ftHandle: FT_HANDLE,
        ucDirection: UCHAR,
        pCallback: FT_NOTIFICATION_CALLBACK,
        pvCallbackContext: PVOID,
        uwCallbackLatency: USHORT,
    ) -> FT_STATUS;
}
unsafe extern "C" {
    pub fn FT_SetTransferParams(pConf: *mut FT_TRANSFER_CONF, dwFifoID: DWORD) -> FT_STATUS;
}
unsafe extern "C" {
    pub fn FT_GetReadQueueStatus(
        ftHandle: FT_HANDLE,
        ucFifoID: UCHAR,
        lpdwAmountInQueue: LPDWORD,
    ) -> FT_STATUS;
}
unsafe extern "C" {
    pub fn FT_GetWriteQueueStatus(
        ftHandle: FT_HANDLE,
        ucFifoID: UCHAR,
        lpdwAmountInQueue: LPDWORD,
    ) -> FT_STATUS;
}
unsafe extern "C" {
    pub fn FT_GetUnsentBuffer(
        ftHandle: FT_HANDLE,
        ucFifoID: UCHAR,
        byBuffer: *mut BYTE,
        lpdwBufferLength: LPDWORD,
    ) -> FT_STATUS;
}
